### ISSUE TITLE
Sending a ticket to someone else in the website

### ISSUE THREAD

**Issue by karimosman** [WISVCH/events#182]

**Comment by svenpopping** [comment]
Do you mean ticket transfers?

**Comment by karimosman** [comment]
yes, but not by giving some else a code, but just on the site itself. Would be a nice feature.

**Comment by merelanne** [comment]
@JoepdeJong Didn't you fix this already?

**Comment by JoepdeJong** [comment]
> @JoepdeJong Didn't you fix this already?


Yes!
