### ISSUE TITLE
Description sent to iDeal is nondescriptive

### ISSUE THREAD

**Issue by GijsWeterings** [WISVCH/events#188]
When sending the user to the iDeal checkout page, the transaction gets the description `W.I.S.V. 'Christiaan Huygens' Payme`. I assume this is getting cut off, but it'd be better to for example list the ordered items in the description, so users can see it properly in their bank statement

**Comment by skamoen** [comment]
As this goes through Payments, I think this should be solved in https://github.com/WISVCH/payments/

**Comment by GijsWeterings** [comment]
True, but I assume it sends this information to payments in some way, right? So it'd need to be edited in 2 places

**Comment by svenpopping** [comment]
At the moment Events does not send a transaction description to Payments.

**Comment by skamoen** [comment]
However, if I understand correctly, Payments knows which products are being ordered so this could be added anyway. It's currently defined statically ([here](https://github.com/WISVCH/payments/blob/master/src/main/java/ch/wisv/payments/rest/MolliePaymentService.java#L58))

**Comment by svenpopping** [comment]
Yes, events just sends a list of products.
