### ISSUE TITLE
Provide option to retry payment after unsuccessful return to site

### ISSUE THREAD

**Issue by GijsWeterings** [WISVCH/events#189]
The site now just says `Order has been successfully cancelled!` with a button to go back to https://ch.tudelft.nl . If an order failed, it may be for another reason besides not wanting to pay anymore (random errors, mistype confirmation code etc)

**Comment by svenpopping** [comment]
@GijsWeterings did you cancel the order or did an error an occur? Because when an error occurs the order will have a different status and the return page will show a different message.

**Comment by GijsWeterings** [comment]
aah. In my case I cancelled (don't have my randomreader with me), but even in this situation, you may want to retry (for example, if you per mistake selected the wrong bank for your iDeal payment)
