### ISSUE TITLE
Events doesn't handle logout

### ISSUE THREAD

**Issue by GijsWeterings** [WISVCH/events#190]
If I'm logged in via events, then log out of CH connect in a different tab, I can still keep ordering (and probably pay for) tickets. This would imply if a user buys tickets on another device, their session is not deauthenticated, making it possible for the owner of the device to keep buying tickets on another user's account

**Comment by svenpopping** [comment]
That's loggin out of CH connect is different then loggin out of Events. 

Loggin out of Events is currently not possible, which should be.

**Comment by svenpopping** [comment]
I just realised that you cannot see which users is currently logged in. Created another issue for that #191.
