### ISSUE TITLE
'description' field doesn't allow long blocks of text (but it should)

### ISSUE THREAD

**Issue by sanderploegsma** [WISVCH/events#23]
While testing I tried to recreate [this](https://ch.tudelft.nl/vereniging/agenda/2016/dinsdag-lunchlezing-informatica-jeroen-de-ridder) particular event, but the description seems to exceed some maximum length.

`2016-01-29 02:07:57.695  WARN 12482 --- [qtp963349287-35] o.h.engine.jdbc.spi.SqlExceptionHelper   : SQL Error: 3401, SQLState: 22001`
`2016-01-29 02:07:57.695 ERROR 12482 --- [qtp963349287-35] o.h.engine.jdbc.spi.SqlExceptionHelper   : data exception: string data, right truncation;  table: EVENT column: DESCRIPTION`

**Comment by RickWieman** [comment]
Hmm, strange... Especially as it should be a blob, according to https://github.com/WISVCH/events/blob/master/src/main/java/ch/wisv/events/model/Event.java#L23...

**Comment by sanderploegsma** [comment]
It says `@Lob` though :smile:

**Comment by RickWieman** [comment]
I know, but that _should_ do the trick >> https://docs.oracle.com/javaee/6/api/javax/persistence/Lob.html

**Comment by praseodym** [comment]
Annotating with both `@Lob` as well as `@Column(length = xyz)` should fix this.

**Comment by sanderploegsma** [comment]
Tried using `length = 512`. This particular use-case works, but if the description is slightly longer it still crashes. For some reason I think the column is still created as `VARCHAR`, although I'm not sure how to check that.

**Comment by jabbink** [comment]
`@Column(columnDefinition="TEXT")`?

**Comment by sanderploegsma** [comment]
That's what I also found, although I remember reading that it isn't compatible with some DB backends, although I can't seem to find it now.

**Comment by jabbink** [comment]
Then I guess a generic approach could be

```@Lob
private byte[] description;
```

and then always properly convert it to a `String`.

![UGLY!](http://gif.co/rFDB.gif)
