### ISSUE TITLE
Increase the maximum size of an event image from 1MB to something more reasonable like 5MB

### ISSUE THREAD

**Issue by Fastjur** [WISVCH/events#271]
**Is your feature request related to a problem? Please describe.**
Many images are larger than 1MB, as most images I use are from a free stock photo website, where decreasing the size to 1MB makes them rather ugly.

**Describe the solution you'd like**
I'd like to increase the maximum size of an image to be increased from 1MB to somewhere around 5 or more.

**Describe alternatives you've considered**
Compressing the images, this, however, doesn't work nicely with large stock photos as they tend to get very ugly.

**Additional context**
Related to #270

**Comment by svenpopping** [comment]
Fixed it -> limit set to 5mb.
