### ISSUE TITLE
Allow committees to access their own ticket sales

### ISSUE THREAD

**Issue by julian9499** [WISVCH/events#319]
**Is your feature request related to a problem? Please describe.**
Currently a  committee is dependent on a member of the board to see into the ticket sales of their events. Some events require a minimal amount of attendance which can mean that the committee has to ask the board for updates frequently. This feature will allow the committee to rely less on the board and do more themselves. 

**Describe the solution you'd like**
This feature has two parts that need to be implemented:
 - A dropdown during the creation of a ticket that allows the creator to assign a committee to the ticket
- A view for the committee member that wants to access their committee's ticket sales which can be accessed through a button in the header or my profile.

**Describe alternatives you've considered**
I thought about coupling this to a separate entity that displays this, but that seems counter intuitive.

**Additional context**

**Comment by svenpopping** [comment]
_A dropdown during the creation of a ticket that allows the creator to assign a committee to the ticket_ already exists.

Guess the best location to add the view is in the sales part of the application (https://ch.tudelft.nl/events/sales)
