### ISSUE TITLE
Codeclimate returns checkstyle syntax error

### ISSUE THREAD

**Issue by julian9499** [WISVCH/events#326]
Okay so I have no idea why this is still erroring. But perhaps we can ignore the codeclimate issue for now and see why it is complaining about this module being a child of `TreeWalker` while it clearly isn't (and is even deleted). @julian9499 I would move this one to be a direct child of `Checker` as per documentation, and then just merge this PR for now and add an issue to look into this. Perhaps codeclimate is just being weird and not using the correct config file, but using the one on the master branch for some stupid reason. Maybe that fixes it, and otherwise we'll have the issue to remind us to fix it. No need to keep the 3 PRs open for now.

_Originally posted by @Fastjur in https://github.com/WISVCH/events/pull/325#discussion_r516809551_

**Comment by Fastjur** [comment]
Turns out my hunch was right: https://github.com/WISVCH/events/pull/322

Codeclimate appears to be using the latest master for the config. Not the config in the branch of the respective PR. It works again in this branch: https://github.com/WISVCH/events/pull/322
