### ISSUE TITLE
Fix order of order and ticket lists in profile

### ISSUE THREAD

**Issue by julian9499** [WISVCH/events#387]
The order of almost all lists under the profile starts with the dates ascending. This means that you have to scroll down for your last tickets.

**Comment by JoepdeJong** [comment]
It is maybe also nice to move non-scanned but expired tickets to the expired part of the My Ticketes page. Makes it a lot clearer.

**Comment by julian9499** [comment]
Good idea

**Comment by julian9499** [comment]
I suggest to put this in a separate issue. After evaluating how to do this I came to the conclusion that it requires quite some heavy SQL queries per ticket to find the end-time of the event bound to a ticket.
