### ISSUE TITLE
Minor frontend issues

### ISSUE THREAD

**Issue by Icety** [WISVCH/events#39]
- [x] Capitals at the page headers:
- products
- edit product
- events
- etc
- [x] All prices with 2 decimals

Edit product
- [x] Max sold -> Available
- [x] Starting time and ending time to dutch writing style (At least no AM/PM)
- [x] Only after Max Sold there is a colon, the rest not 
- [x] If you fill in 0 at Max sold, does that mean that its infinite?

**Comment by svenpopping** [comment]
`Starting time and ending time to dutch writing style (At least no AM/PM)` is depending on you browser setting
