### ISSUE TITLE
Form for the analysis of event promotion

### ISSUE THREAD

**Issue by JoepdeJong** [WISVCH/events#391]
**Is your feature request related to a problem? Please describe.**
The board is analyzing their promotion. They want to know how people found out about the event. For this, they made a [Google Form](https://forms.gle/qbtJae9wFFw5hLwr9) that can be filled in after buying a ticket.

**Describe the solution you'd like**
Possibility to directly show a Google Form after buying a ticket. They want it **embedded** in the page.

**Describe alternatives you've considered**
#381 allows adding redirect URLs to a product. This is very useful for event-specific forms e.g. dinner forms. 
The form that is now requested will be the same for every event and will be used indefinitely. Using the functionality of #381 seems not optimal.

**Additional context**
I am not sure if showing this form at the end of every order makes sense. People will ignore it after they fill it in once. Are there other ways to ask the customer for a response?

**Comment by JoepdeJong** [comment]
@julian9499 What do you think of embedding the form in the success page?

**Comment by julian9499** [comment]
I think it'll work. It will however maybe interfere with the current form option for products. Maybe it's better to do a small pop up once they put a ticket in their cart?
