### ISSUE TITLE
Save events in Google Calendar for a year

### ISSUE THREAD

**Issue by Amandaatje** [WISVCH/events#408]
**Is your feature request related to a problem? Please describe.**
After someone added the events calendar to their own Google Calendar, all the future activities are visible. However, when an event is over, the item will be deleted in the Google Calendar. The user is not able to view past activities in their own calendar.

**Describe the solution you'd like**
I would like to view the activity for a year in my own Google Calendar.

**Describe alternatives you've considered**
Instead of a year, to be able to view the activities for a quarter or month.

**Comment by JoepdeJong** [comment]
Opened PR https://github.com/WISVCH/wisvch-wordpress-plugin/pull/14

**Comment by Amandaatje** [comment]
Yes that is correct! But then preferably from the last year instead of last week
