### ISSUE TITLE
Redirect admin panel button to events instead of overview

### ISSUE THREAD

**Issue by shirleyxindi** [WISVCH/events#409]
I'm fixing this, but can't assign myself, just so everyone knows :)

**Is your feature request related to a problem? Please describe.**
The overview page of the admin panel loads very slowly. So if you click the 'Admin panel' button it takes quite some time to get to the admin page. 

**Describe the solution you'd like**
The admin panel button should redirect to the events page instead of the overview page. 

**Describe alternatives you've considered**
Make the overview page load faster. This solution would be better of course, but in the mean time we can fix the problem by redirecting it to the events page, which loads much faster.

**Comment by JoepdeJong** [comment]
The overview page loads already faster.
