### ISSUE TITLE
Email address not linked to Dienst

### ISSUE THREAD

**Issue by merelanne** [WISVCH/events#410]
**Describe the bug**
Events stores a user with an email address (I think), instead of requesting the email address from Dienst. I can't change my email address in Events either. 

**To Reproduce**
1. Change your email address in Dienst (to see the difference)
2. Go to 'wisv.ch/events'
3. Click on login and login with your credentials
4. Make an order
5. Go to "My events" and click on the order that was made after changing the email address in Dienst to check which email address is used
6. See that it's a different email address than in Dienst. 

**Expected behavior**
The email address from Dienst is used (preferred) or there is a functionality in events to change your email address.

**Screenshots**
_Events (after step 2 - 6)_
![events](https://user-images.githubusercontent.com/44727706/191208908-3e0dc7c0-8b16-460b-a2fb-e1757cc2aeca.png)
**Desktop**
 - Browser: Chrome
 - Version 105.0.5195.127

_Dienst_
![dienst](https://user-images.githubusercontent.com/44727706/191208604-47ab3eec-996b-4c51-9b35-54a7785b798d.png)
**Desktop**
 - Browser: Chrome
 - Version 105.0.5195.127

**Comment by julian9499** [comment]
fixed1
