### ISSUE TITLE
Fix url/link root

### ISSUE THREAD

**Issue by svenpopping** [WISVCH/events#69]
Some of the links will direct you to the main website, because the root in development is `/`, but the root in production should be `/events`. Use `th:href=@{/path/to/whatever}`

- [x] Link of the header logo
- [x] Links on the main page https://ch.tudelft.nl/events/
- [x] Ajax calles to product api

**Comment by skamoen** [comment]
note: Easy to test in dev environment by setting `server.context-path=/events/`. It will then run on `localhost:{PORT}/events/`

Also easy to fix with thymeleaf `th:href="@{/path/to/whatever}"`, as Thymeleaf will figure out the proper link.

**Comment by svenpopping** [comment]
Most links use already `th:href="@{/path/to/file}"`, but some do not. So those need to be fixed.
